---
channel: edge
addons:
  codeproject-ai-server-dev:
    repository: stevusprimus-hassio-addons/addon-codeproject-ai-server
    target: codeproject-ai-server
    image: ghcr.io/stevusprimus-hassio-addons/codeproject-ai-server/{arch}
