---
channel: edge
addons:
  codeproject-ai-server-dev:
    repository: stevusprimus/hassio-addon-codeproject-ai-server
    target: codeproject-ai-server-dev
    image: ghcr.io/stevusprimus/hassio-addon-codeproject-ai-server/{arch}