---
name: Sync labels

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "34 5 * * *"
  workflow_dispatch:

jobs:
  workflows:
    uses: stevusprimus-hassio-addons/workflows/.github/workflows/labels.yaml@main
