---
name: Lint

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

# yamllint disable-line rule:line-length
jobs:
  workflows:
    uses: stevusprimus-hassio-addons/workflows/.github/workflows/repository-lint.yaml@main
