---
name: PR Labels

# yamllint disable-line rule:truthy
on:
  pull_request_target:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

jobs:
  workflows:
    # yamllint disable-line rule:line-length
    uses: stevusprimus-hassio-addons/workflows/.github/workflows/pr-labels.yaml@main
